        "+", "add", mdscal,
        "-", "subtract", mdscal,
        "X", "multiply", mdscal,
        "%", "divide", mdscal,
        "|", "absolute value", mdscal,

        "(", "left paren", lpar,
        ")", "right paren", rpar,
        "[", "left bracket", lbkt,
        "]", "right bracket", rbkt,

        "/", "reduce", com,
        "-@/", "reduce on first axis", com0,
        "\\", "scan", com,
        "-@\\", "scan on first axis", com0,

        "G", "del", dell,
        "'", "quote", strng,
        "J", "outer product", null,
        ".", "inner product", dot,
        "L", "quad", q_var,
        ";", "semicolon", semi,
        ":", "colon", colon,
        "}", "right arrow", tran,
        "<", "less than", dscal,
        ">", "greater than", dscal,
        "=", "equal", dscal,
        "^", "and", dscal,
        "V", "or", dscal,
        "D", "smaller", mdscal,
        "S", "larger", mdscal,
        "*", "power", mdscal,
        "O", "circle", mdscal,
        "!", "factorial", mdscal,
        "~", "not", m,
        "N", "encode", d,
        "B", "decode", md,
        "Y", "take", d,
        "U", "drop", d,
        "{", "assign", asg,
        "E", "element of", md,
        "?", "deal", md,
        "R", "dimension", md,
        "I", "index", md,
        ",", "concatenate", mdsub,
        "\'@L", "quote quad", q_var,
        "J@C", "comment", comnt,
        "<@= or $", "less than or equal", dscal,
        ">@= or &" "greater than or equal", dscal,
        "/@= or #", "not equal", dscal,
        "~@^", "not and (nand)", dscal,
        "~@V", "not or (nor)", dscal,
        "*@O", "log", mdscal,
        "J@N", "format", md,
        "J@B", "execute", m,
        "O@|", "rotate", mdsub,
        "O@-", "rotate on first axis", md,
        "O@\\", "transpose", md,
        "B@N", "I-beam", md,
        "%@L", "linear regression", md,
        "|@H", "grade up", msub,
        "|@G", "grade down", msub,
        "123", "number"
        "123.4", "number"
        "`123.4", "number"
        "1.2e2", "number"
        "1.2e`2", "number"
